# Generated by Django 2.2.4 on 2019-08-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=500)),
                ('scope', models.CharField(choices=[('Co', 'Country'), ('Re', 'Region'), ('Pr', 'Province'), ('Di', 'District')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
