# Generated by Django 2.2.4 on 2019-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
