# Generated by Django 2.2.4 on 2019-08-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20190815_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url_base',
            field=models.TextField(default='https://infogob.jne.gob.pe/Localidad/Peru'),
        ),
    ]
