# Generated by Django 2.2.4 on 2019-08-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_url_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='url_base',
            field=models.TextField(default='https://infogob.jne.gob.pe/Localidad/'),
        ),
    ]
